name = "osep-judge-visit-counter"
main = "src/index.js"
compatibility_date = "2026-08-31"

[vars]
# 允許呼叫的前端網域（正式環境+本機開發），多個網域用逗號分隔，不含結尾斜線
ALLOWED_ORIGINS = "https://p2766602-beep.github.io,http://localhost:8601"

[[kv_namespaces]]
binding = "VISIT_COUNTER"
id = "88a4a90fa9ea46138c8a8b6e869ca498"
